/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Vivek' at '2/26/17 12:17 PM' with Gradle 2.9
 *
 * @author Vivek, @date 2/26/17 12:17 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
